// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WLEPiO3wBLmaSlGWfRG6kyRIEvqLUZA',
    appId: '1:1033268343411:web:97a29b7448ace55fe03006',
    messagingSenderId: '1033268343411',
    projectId: 'quickfooddeals',
    authDomain: 'quickfooddeals.firebaseapp.com',
    storageBucket: 'quickfooddeals.appspot.com',
    measurementId: 'G-YNYW31T63W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdv4R74w-iPMCqQKVTDadJgVXxr4o6Mg',
    appId: '1:1033268343411:android:fecc2fbd6b8b678ce03006',
    messagingSenderId: '1033268343411',
    projectId: 'quickfooddeals',
    storageBucket: 'quickfooddeals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xvXZg2ySheJsZN0VsDyq8XE7NQDKXC4',
    appId: '1:1033268343411:ios:e015f1f41aabd277e03006',
    messagingSenderId: '1033268343411',
    projectId: 'quickfooddeals',
    storageBucket: 'quickfooddeals.appspot.com',
    iosClientId: '1033268343411-0aucvk1r44s47btjpls90kpfo15ooas8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCubit',
  );
}
